name: backend-deployment
on:
  push:
    branches:
      - staging
    paths:
      - "backend/**"

jobs:
  deploy:
    name: deploy
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./backend && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}