name: backend-tests
on:
  pull_request:
    branches:
      - "*"
    paths:
      - "backend/**"

jobs:
  backend-test:
    name: backend-test
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
